// ══════════════════════════════════════════════════════════════════════════════
// MuseEngine.js — companion mode intelligence layer
//
// Four jobs:
//   1. GATE    — mutes Heartbeat autonomy while companion mode is active
//   2. EXTRACT — derives live concepts from conversation (frequency + LLM themes)
//   3. ARC     — classifies conversation phase using multi-signal scoring
//   4. INSIGHT — generates periodic pattern/connection/challenge notices for Studio
// ══════════════════════════════════════════════════════════════════════════════

import { EventEmitter } from 'events';

const STOP = new Set([
    'the','a','an','and','or','but','in','on','at','to','for','of','with','by',
    'from','is','are','was','were','be','been','being','have','has','had','do',
    'does','did','will','would','could','should','may','might','can','shall',
    'it','its','this','that','these','those','i','you','he','she','we','they',
    'me','him','her','us','them','my','your','his','our','their','what','which',
    'who','how','when','where','why','just','like','so','very','really','about',
    'up','out','if','then','than','too','also','into','over','after','before',
    'here','there','now','still','even','back','any','each','most','more','some',
    'such','no','not','only','same','other','yeah','okay','yes','kind','think',
    'know','going','want','need','make','take','get','got','let','say','said',
    'well','actually','literally','basically','thing','things','stuff','bit',
    'lot','way','mean','look','feel','feels','felt','seems','seem','seemed',
    'const', 'let', 'var', 'function', 'class', 'import', 'export', 'return',
    'await', 'async', 'yield', 'true', 'false', 'null', 'undefined', 'console',
    'log', 'error', 'debug'
]);

const ARC_WAVEFORM = {
    opening:   'listening',
    exploring: 'thinking',
    deepening: 'speaking',
    resolving: 'reflecting',
};

const ARC_AMBIENT = {
    opening:   { intensity: 0.40, warmth: 0.40 },
    exploring: { intensity: 0.55, warmth: 0.55 },
    deepening: { intensity: 0.70, warmth: 0.65 },
    resolving: { intensity: 0.50, warmth: 0.70 },
};

// Classify an insight body into kind + title from actual content keywords
function classifyInsight(text) {
    const t = text.toLowerCase();
    if (/pattern|repeat|recurring|again|keep|always|tend|cycle|habit/.test(t))
        return { kind: 'pattern',    title: 'a pattern is repeating' };
    if (/connect|link|between|relate|bridge|both|similar|analog|parallel/.test(t))
        return { kind: 'connection', title: 'strange connection' };
    if (/risk|problem|issue|challenge|concern|careful|danger|warn|fail|block/.test(t))
        return { kind: 'challenge',  title: 'worth pushing back on' };
    if (/discover|novel|new|first|never|unexpected|surprise|interesting/.test(t))
        return { kind: 'connection', title: 'something unexpected' };
    return { kind: 'pattern', title: 'noticing something' };
}

export class MuseEngine extends EventEmitter {
    constructor() {
        super();
        this._active      = false;
        this._concepts    = [];
        this._arc         = 'opening';
        this._turnCount   = 0;
        this._heartbeat   = null;
        this._lastMessages = [];
        this._insights    = [];          // Studio notices — generated by LLM
        this._lastInsightAt = 0;        // turn count of last insight generation
        this._insightPending = false;   // debounce concurrent requests
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    activate(heartbeat) {
        if (this._active) return;
        this._active       = true;
        this._arc          = 'opening';
        this._turnCount    = 0;
        this._concepts     = [];
        this._insights     = [];
        this._lastInsightAt = 0;

        this._heartbeat = heartbeat;
        if (heartbeat) heartbeat.mute();

        this.emit('activated', this.getState());
        console.log('[MuseEngine] ✦ Companion mode — autonomy muted, muse active');
    }

    deactivate() {
        if (!this._active) return;
        this._active = false;

        if (this._heartbeat) {
            this._heartbeat.unmute();
            this._heartbeat = null;
        }

        this.emit('deactivated');
        console.log('[MuseEngine] ✦ Companion mode off — autonomy restored');
    }

    isActive() { return this._active; }

    // ── Ingest a message exchange ─────────────────────────────────────────────

    ingest(messages) {
        if (!this._active) return;

        this._lastMessages = messages;
        this._turnCount    = messages.filter(m => m.role === 'user').length;
        this._concepts     = this._extractConcepts(messages);
        this._arc          = this._classifyArc(messages);

        // Every 4 user turns, request a fresh insight for Studio
        const turnsSinceLast = this._turnCount - this._lastInsightAt;
        if (turnsSinceLast >= 4 && this._turnCount >= 2 && !this._insightPending) {
            this._lastInsightAt = this._turnCount;
            this.emit('needs_insight', {
                messages: messages.slice(-10),
                concepts: this._concepts,
            });
        }

        const state = this.getState();
        this.emit('muse_state', state);
        return state;
    }

    // ── Called by MAX.js after the LLM generates an insight ──────────────────

    publishInsight(text) {
        if (!text || !text.trim()) return;
        this._insightPending = false;
        const { kind, title } = classifyInsight(text);
        const strength = Math.min(1.0, Math.max(0.45, text.length / 280));
        const insight  = { kind, title, body: text.trim().slice(0, 220), strength, ts: Date.now() };
        this._insights.unshift(insight);
        if (this._insights.length > 8) this._insights.pop();
        this.emit('muse_insight', insight);
    }

    markInsightPending() { this._insightPending = true; }
    clearInsightPending() { this._insightPending = false; }

    // ── State snapshot ────────────────────────────────────────────────────────

    getState() {
        const ambient = ARC_AMBIENT[this._arc] || ARC_AMBIENT.opening;
        return {
            active:    this._active,
            arc:       this._arc,
            turnCount: this._turnCount,
            concepts:  this._concepts,
            insights:  this._insights,
            waveform:  ARC_WAVEFORM[this._arc] || 'listening',
            ambient,
        };
    }

    // ── Private ───────────────────────────────────────────────────────────────

    _extractConcepts(messages) {
        const recent = messages.slice(-16);
        const freq   = new Map();

        for (let idx = 0; idx < recent.length; idx++) {
            const m = recent[idx];
            // Exponential decay: older messages (smaller idx) are decayed by 0.90 per message distance
            const distance = recent.length - 1 - idx;
            const decay = Math.pow(0.90, distance);
            const baseWeight = m.role === 'user' ? 2.0 : 1.0;
            const weight = baseWeight * decay;

            const words  = this._getText(m)
                .toLowerCase()
                .replace(/[^a-z0-9\s'-]/g, ' ')
                .split(/\s+/)
                .filter(w => w.length > 3 && !STOP.has(w));

            for (const w of words) {
                freq.set(w, (freq.get(w) || 0) + weight);
            }
            for (let i = 0; i < words.length - 1; i++) {
                if (!STOP.has(words[i]) && !STOP.has(words[i + 1])) {
                    const bg = `${words[i]} ${words[i + 1]}`;
                    freq.set(bg, (freq.get(bg) || 0) + weight * 1.4);
                }
            }
        }

        return [...freq.entries()]
            .filter(([k]) => k.length > 5)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 14)
            .map(([k]) => k);
    }

    // Multi-signal arc scoring — replaces pure turn-count thresholds
    _classifyArc(messages) {
        if (this._turnCount === 0) return 'opening';

        let score = this._turnCount * 2;

        // Question density in recent user turns — signals active exploration
        const recentUser = messages.filter(m => m.role === 'user').slice(-5);
        const questions  = recentUser.filter(m => this._getText(m).includes('?')).length;
        score += questions * 3;

        // Average MAX response length — longer = more engaged / deepening
        const recentMax = messages.filter(m => m.role === 'assistant' || m.role === 'max').slice(-3);
        const avgLen    = recentMax.length
            ? recentMax.reduce((s, m) => s + this._getText(m).length, 0) / recentMax.length
            : 0;
        score += Math.min(avgLen / 80, 6);

        // Resolution signals in last user message — they're wrapping up
        const last = recentUser[recentUser.length - 1];
        if (last) {
            const t = this._getText(last).toLowerCase();
            if (/thanks|perfect|got it|makes sense|exactly|that.s it|clear|understood/.test(t)) score += 12;
        }

        if (score < 6)  return 'opening';
        if (score < 20) return 'exploring';
        if (score < 40) return 'deepening';
        return 'resolving';
    }

    _getText(m) {
        if (typeof m.content === 'string') return m.content;
        if (m.text)                        return m.text;
        if (Array.isArray(m.content))      return m.content[0]?.text || '';
        return '';
    }
}
